import { buildStandaloneHtml } from './buildStandaloneHtml';
import { createManifest } from './createManifest';
import type { ExportBundle, ExportBundleBuildInput } from './types';

function extractTagContent(html: string, tag: 'style' | 'script'): string {
  const match = html.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, 'i'));
  return match?.[1]?.trim() ?? '';
}

function buildLinkedIndexHtml(html: string): string {
  return html
    .replace(/<style>[\s\S]*?<\/style>/i, '<link rel="stylesheet" href="./styles.css">')
    .replace(/<script>[\s\S]*?<\/script>/i, '<script src="./script.js"></script>');
}

function buildHandoffMarkdown(bundle: ExportBundle): string {
  const { manifest } = bundle;
  return [
    `# ${manifest.name}`,
    '',
    '## Context',
    '',
    `- Artifact: ${manifest.artifactType}`,
    `- Direction: ${manifest.directionId}`,
    `- Theme: ${manifest.themeId}`,
    `- Created: ${manifest.createdAt}`,
    `- Quality score: ${manifest.quality.total}/10`,
    '',
    '## Brief',
    '',
    manifest.brief.prompt,
    '',
    '## UX Intent',
    '',
    `- Domain: ${manifest.intent.domain}`,
    `- Goal: ${manifest.intent.goal}`,
    `- Primary action: ${manifest.intent.primaryAction}`,
    '',
    '## Planned Modules',
    '',
    ...manifest.intent.modules.map((module) => `- ${module.label}: ${module.purpose}`),
    '',
    '## Quality Issues',
    '',
    ...(manifest.quality.issues.length > 0
      ? manifest.quality.issues.map((issue) => `- [${issue.severity}] ${issue.title}: ${issue.suggestedFix}`)
      : ['- No blocking issues found by the local analyzer.']),
    '',
    '## Continue In An Agent',
    '',
    bundle.files['README.md'],
  ].join('\n');
}

function buildBundleReadme(manifestName: string): string {
  return [
    `# ${manifestName} Export`,
    '',
    'This folder was generated by Designme Studio.',
    '',
    '- Open `index.html` directly in a browser. No server is required.',
    '- Edit `styles.css` and `script.js` for quick iteration.',
    '- Read `designme.json` for prompt, intent, tweaks, direction and quality metadata.',
    '- Use `handoff.md` as context for Codex, Claude or another design/dev agent.',
  ].join('\n');
}

export function buildExportBundle(input: ExportBundleBuildInput): ExportBundle {
  const html = buildStandaloneHtml(input.output);
  const manifest = createManifest(input);
  const readme = buildBundleReadme(input.output.name);
  const bundle: ExportBundle = {
    name: input.output.exportName,
    manifest,
    files: {
      'index.html': buildLinkedIndexHtml(html),
      'styles.css': extractTagContent(html, 'style'),
      'script.js': extractTagContent(html, 'script'),
      'designme.json': JSON.stringify(manifest, null, 2),
      'handoff.md': '',
      'README.md': readme,
    },
  };

  bundle.files['handoff.md'] = buildHandoffMarkdown(bundle);
  return bundle;
}
