import { deriveBrief } from './brief';
import { buildAssumptions, buildCritique } from './critique';
import { buildHandoffPrompt } from './handoff';
import { applyIntentToBrief, resolveIntent } from './intent';
import { directionById } from './options';
import { buildHtml } from './render/htmlDocument';
import type { BuildInput, DesignOutput } from './types';
import { slugify } from './utils';

export * from './options';
export * from './types';
export * from './intent';

export function buildDesignProject(input: BuildInput): DesignOutput {
  const direction = directionById(input.directionId);
  const brief = deriveBrief(input.prompt, input.artifactType);
  const intent = resolveIntent(brief, input.artifactType);
  const enrichedBrief = applyIntentToBrief(brief, intent);
  const html = buildHtml(enrichedBrief, input.artifactType, direction, input.tweaks, intent);
  const critique = buildCritique(enrichedBrief, input.artifactType, direction, input.tweaks, intent, html);
  return {
    name: enrichedBrief.name,
    exportName: slugify(`${enrichedBrief.name}-${input.artifactType}`),
    briefSummary: `${enrichedBrief.objective} para ${enrichedBrief.audience}.`,
    brief: {
      rawPrompt: enrichedBrief.rawPrompt,
      topic: enrichedBrief.topic,
      audience: enrichedBrief.audience,
      objective: enrichedBrief.objective,
    },
    assumptions: buildAssumptions(enrichedBrief, direction, intent),
    sections: enrichedBrief.sections,
    features: enrichedBrief.features,
    html,
    handoffPrompt: buildHandoffPrompt(enrichedBrief, input.artifactType, direction, input.tweaks, intent),
    critique,
    direction,
    intent,
  };
}

/**
 * Re-evaluate the engine's quality pass on HTML generated by an external provider.
 * Keeps the deterministic brief/intent/direction/handoff context as scaffolding,
 * but replaces the HTML and re-runs the local quality analyzer over it so the
 * critique panel reflects the actual artifact instead of the deterministic fallback.
 */
export function rebuildDesignOutputWithHtml(input: BuildInput, html: string): DesignOutput {
  const direction = directionById(input.directionId);
  const brief = deriveBrief(input.prompt, input.artifactType);
  const intent = resolveIntent(brief, input.artifactType);
  const enrichedBrief = applyIntentToBrief(brief, intent);
  const critique = buildCritique(enrichedBrief, input.artifactType, direction, input.tweaks, intent, html);
  return {
    name: enrichedBrief.name,
    exportName: slugify(`${enrichedBrief.name}-${input.artifactType}`),
    briefSummary: `${enrichedBrief.objective} para ${enrichedBrief.audience}.`,
    brief: {
      rawPrompt: enrichedBrief.rawPrompt,
      topic: enrichedBrief.topic,
      audience: enrichedBrief.audience,
      objective: enrichedBrief.objective,
    },
    assumptions: buildAssumptions(enrichedBrief, direction, intent),
    sections: enrichedBrief.sections,
    features: enrichedBrief.features,
    html,
    handoffPrompt: buildHandoffPrompt(enrichedBrief, input.artifactType, direction, input.tweaks, intent),
    critique,
    direction,
    intent,
  };
}
